white_cards = [
    "Uma maldição cigana", "Herpes labial", "Um pelo pubiano", "Um momento de silêncio", "Cachalotes",
    "Fraternidades judias", "Um festival da linguiça", "Chacota", "Cotas Raciais", "Um policial honesto sem nada a perder",
    "Moradores de rua", "Fazer aquilo na bunda", "Escassez de comida", "Dar uns amassos", "Ensinar um robô a amar",
    "Bactéria carnívora", "Incesto", "Ser foda", "Erva para aumentar a libido", "Ejaculação precoce",
    "Um moinho de vento cheio de cadáveres", "Não dar a mínima para o Terceiro Mundo", "Um mímico tendo um AVC",
    "Toddynho", "Sexting", "Hulk Hogan", "Vestir roupa íntima ao avesso pra economizar uma lavada",
    "Transmutação corpórea", "Deus", "Um raio da morte", "Atrizes pornô", "Coçar sob as dobras da pele",
    "Teto de vidro", "Criancinhas", "Urofilia", "Um congelador cheio de órgãos", "Estuprar e saquear", "Emoções",
    "O Sonho Americano", "72 virgens", "Lamber coisas para estabelecer que são propriedade sua", "Barriga de chopp",
    "Fuzilamento", "Cerveja quente", "Quando você peida e sai mais do que devia", "Um paradoxo de viagem no tempo.",
    "A placenta.", "Pegar de volta o que foi dado.", "Autêntica cozinha mexicana.", "Combustão espontânea.", "Bebês mortos.",
    "Cintilante.", "Amizade colorida.", "Prepúcio.", "Consultores.", "Pintar com os dedos.", "Solos de saxofone.", "Dívida monstruosa.",
    "Cheiro de pessoa velha.", "Italianos.", "Problemas com o pai na infância.", "Morrer de disenteria.", "Um feto.",
    "Balbúrdia.", "Meus demônios interiores.", "Disparar uma espingarda para o alto enquanto trepa com uma cabra que está aos berros.",
    "Dentro em breve.", "Pistola d'água cheia de urina de gato.", "Gugu.", "Cotas raciais.", "Chamego.", "Amputados.",
    "Deixar o lustre cair sobre seus inimigos enquanto a outra ponta da corda te lança pra cima.", "Didi.", "Eugenia.",
    "O ex-presidente Michel Temer.", "A crônica.", "O status de minha relação.", "Nudez frontal.", "Rinha de galo.",
    "Nicolas Cage.", "Injeções hormonais.", "Fogo amigo.", "Abelhas.", "Pôr um ovo.", "Fernando Collor", "Erotismo baseado em Harry Potter.",
    "Assistir TV globinho pelado(a).", "Uma festa de aniversário decepcionante.", "Faculdade.", "Fingir que se importa.",
    "Uma mulher atrevida.", "Ficar bebâdo ao bochechar antisséptico bucal.", "Pagar mico em público.", "Atleta de olimpíada de matemática.",
    "Nazistas.", "Compartilhar agulhas.", "Um cavalo minúsculo.", "200 gramas de doce heroína preta mexicana.", "Meleca de nariz.",
    "Faustão.", "Stephen Hawking dizendo coisas obscenas.", "Stephen Hawking dizendo coisas sedutoras.", "A inevitável morte do universo.",
    "Cavalgar rumo ao por do sol.", "Pais mortos.", "O milagre do parto.", "Uma reviravolta num roteiro de M. Night Shyamalan.",
    "Permanência do objeto.", "O apocalipse.", "Judeu de cabelo afro.", "Polegares opositores.", "Passar o rodo.", "Pedófilos.",
    "Questões racistas em vestibular.", "Uma pentada violenta.", "Fungos.", "Falar abobrinha.", "No grau.", "Roubar sepultura.",
    "Motosseras.", "O privilégio de ser branco.", "Comer o último bisão conhecido.", "Silvio Santos.", "Deveres de esposa.",
    "Catapultas.", "Concursos de beleza para crianças.", "Recatada.", "Os pobres.", "Explosões.", "Uma viagem para pelotas.",
    "O doce veneno do escorpião.", "Cheirar cola.", "Desodorante AXE®.", "Proibidão.", "Repressão.", "O sangue de Cristo.", "A força",
    "Boa noite, Cinderela.", "Horríveis acidentes causados por depilação a laser.", "Limpar a bunda dela.", "Minha vagina.", "BATMAN!",
    "Design Inteligente.", "Biquini fio-dental."
]


black_cards = [
    "Resolução da ANAC agora proíbe ______ em aeronaves",
    "É uma pena que as crianças hoje em dia estejam envolvidas em ______",
    "Em 1000 anos, quando o dinheiro de papel for apenas uma lembrança distante, ______ será a nossa moeda",
    "CBF proíbe ______ por proporcionar vantagem desleal aos jogadores",
    "Qual é o prazer proibido do Batman? ______",
    "Vem aí o novo livro de J. K. Rowling: Harry Potter e a câmara de ______",
    "Desculpe, professora, mas é que eu não pude terminar o dever de casa por causa de ______",
    "O que eu trouxe do Paraguai? ______",
    "______? Tem um app pra isso",
    "______. Aposto que um só não te satisfaz",
    "Qual é meu anti-droga? ______",
    "Enquanto os Estados Unidos e a União Soviétiva competiam na corrida espacial, o governo brasileiro investia pesado em ______",
    "No novo filme da Disney, Hanna Montana enfrenta ______ pela primeira vez",
    "Qual é meu poder secreto? ______",
    "Qual é a dieta do momento? ______",
    "O que o Vin Diesel teve no jantar? ______",
    "Quando o faraó permaneceu imóvel, Moisés invocou dos céus a praga dos ______",
    "Como estou mantendo minha atual relação amorosa? ______",
    "Qual é o cúmulo da porquice? ______",
    "Dizem que em Bangu 3 se troca dez maços de cigarro por ______",
    "Depois do terremoto, o Elon Musk levou ______ ao Haití",
    "No próximo natal o Papai Noel vai dar ______ pra criança que não se comportar",
    "A vida dos índios americanos mudou para sempre quando o homem branco lhes apresentou ______",
    "Talvez ela tenha nascido assim. Talvez seja ______",
    "Em seus momentos finais, Michael Jackson pensou em ______",
    "Homem branco gosta de ______",
    "Por que estou todo doído? ______",
    "Um jantar romântico à luz de velas seria incompleto sem ______",
    "O que eu levaria ao passado para convencer as pessoas de que eu sou um mágico poderoso? ______",
    "Em breve, numa livraria perto de você, ______",
    "A excursão escolar foi um diasco devido a ______",
    "Qual é o melhor amigo de uma garota? ______",
    "Doutor Drauzio, estou tendo problemas com ______ e gostaria de ouvir seu conselho",
    "Quando eu for presidente, criarei o Departamento de ______",
    "O que os meus pais estão escondendo de mim? ______",
    "O que é que nunca falha em deixar uma festa mais animada? ______",
    "O que é que fica melhor quando envelhece? ______",
    "______: bom até a última gota",
    "Estou com 99 problemas, mas ______ não é um deles",
    "______. É uma armadilha!",
    "Novo reality-show da MTV apresenta oito celebridades desgastadas morando com ______",
    "O que é que vovô acharia perturbador, mas estranhamente charmoso? ______",
    "O que é mais EMO? ______",
    "Durante o sexo, gosto de pensar em ______",
    "O que causou o fim da minha última relação? ______",
    "Que som é esse? ______",
    "______. É assim que eu espero morrer.",
    "Por que minha pele está pegajosa? ______",
    "Qual é o próximo brinde do McLanche Feliz? ______",
    "O que é que tem à vontade no Céu? ______",
    "Não sei com que armas se lutará a terceira guerra mundial, mas a quarta será com ______",
    "O que é tiro-e-queda para se conseguir sexo? ______",
    "______: testado pelas crianças, aprovado pelas mães",
    "Por que não consigo dormir à noite? ______",
    "Que cheiro é esse? ______",
    "O que ajuda o Obama a relaxar depois do trabalho? ______",
    "Assim expira o mundo / Assim expira o mundo / Não com uma explosão, mas com ______",
    "Chega à Broadway nesta temporada o musical ______",
    "Antropólogos recentemente descobriram uma tribo primitiva que cultua ______",
    "Mas, antes de matá-lo, Sr. Bond, preciso te mostrar ______",
    "Estudo mostra que ratos de laboratório atravessam labirintos 50% mais rápido depois de serem expostos à ______",
    "A seguir, na ESPN2: Campeonato Mundial de ______",
    "Quando eu for bilionário, manderei fazer uma estátua de 15 metros de altura para celebrar ______",
    "Buscando aumentar sua audiência, o Museu de História Natural abriu uma exposição interativa sobre ______",
    "Guerra? pra que serve? ______",
    "O quue me causa gases incontroláveis? ______",
    "Idosos têm cheiro de quê? ______",
    "O que vou deixar de fazer na quaresma? ______",
    "A medicina alternativa agora está explorando os poderes curativos de ______",
    "O que os Estados Unidos jogaram, de avião, nas crianças do Afeganistão? ______",
    "O que o Fernando Collor prefere? ______",
    "Historiadores encontram dezenas de cadernos de Picasso com esboços de ______",
    "O que você espera não achar em seu prato de comida chinesa? ______",
    "Bebo pra esquecer ______",
    "______. Tô dentro!",
    "______. As mina pira, véi",
    "______. véi, na moral..."
]
